### ISSUE TITLE
viewDidLoad called twice in DemoTabBarController

### ISSUE THREAD

**Issue by ekkelenkamp** [bfeher/BFPaperTabBarController#13]
Hi,

I really like the bFPaperTabBarController. I tried using it in a project and noticed my view controller that extends the BFPaperTabBarController is called twice.
I checked with the demo that is provide with the source code: DemoTabBarController. There the same happens.
Is there any way to prevent this? Allocating the controller twice seems a bug to me.

Regards,

Rudie.

**Comment by bfeher** [comment]
Hi @ekkelenkamp !

Thanks for bringing this to my attention. After some debugging, I found the offending line of code in BFPaperTabBarController.m:
```
    [self.view addSubview:self.invisibleTouchView];
```

This discovery led me to another possible bug and both will be fixed in the next release. I'll let you know as soon as I push the update.

Thanks again!

**Comment by bfeher** [comment]
Just pushed version 2.1.11 which fixes this bug. 
Cheers!

**Comment by ekkelenkamp** [comment]
Hi,

Great work fixing this bug that fast! I just tested the 2.1.11 version and all works fine now. Keep up the good work!

Rudie.
